from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping


def _escape(value: str) -> str:
    return value.replace("'", "''")


def _to_sql_value(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    return f"'{_escape(str(value))}'"


@dataclass
class SQLBatchWriter:
    out_path: Path

    def begin(self) -> None:
        self.out_path.parent.mkdir(parents=True, exist_ok=True)
        self.out_path.write_text("-- Generated by hoopslab-etl\n", encoding="utf-8")

    def commit(self) -> None:
        with self.out_path.open("a", encoding="utf-8") as f:
            f.write("-- End of generated SQL\n")

    def insert_many_ignore(
        self, table: str, rows: list[Mapping[str, Any]], columns: list[str]
    ) -> None:
        if not rows:
            return
        cols = ", ".join(columns)
        values_sql = ",\n".join(
            "(" + ", ".join(_to_sql_value(row.get(c)) for c in columns) + ")" for row in rows
        )
        sql = f"INSERT OR IGNORE INTO {table} ({cols}) VALUES\n{values_sql};\n"
        with self.out_path.open("a", encoding="utf-8") as f:
            f.write(sql)

    def write_sql(self, sql: str) -> None:
        with self.out_path.open("a", encoding="utf-8") as f:
            f.write(f"{sql.rstrip()}\n")
