/**
 * Regenerates every artifact this repository derives rather than writes.
 *
 * `.prettierignore` and `eslint.config.mjs` have both carried the line
 * "Generated. Regenerate with `npm run gen`, never hand-edit" since phase 3,
 * pointing at four paths. None of the four existed and there was no `gen`
 * script — the convention was declared and never built, so the serving
 * contract, the TypeScript client and the error documentation were each
 * maintained by hand in a repository whose front page argues against exactly
 * that.
 *
 * What is generated, and from what:
 *
 *   contracts/openapi.json                  the app's own route definitions
 *   apps/web/src/lib/api/generated/types.ts that document
 *   docs/errors.md                          ERROR_CODES in http/schemas.ts
 *   docs/data-dictionary.md                 the Drizzle schema + gold contracts
 *
 * The point is not the files. It is that `npm run gen && git diff --exit-code`
 * turns any divergence between the code and its documentation into a red
 * build, so a route added without a schema, or an error code added without an
 * explanation, cannot reach main.
 *
 * Run with tsx rather than node's type stripping: `engines` allows Node 22,
 * where stripping needs a flag, and a generator that works on the author's
 * machine and not in CI is worse than no generator.
 */

import { execFileSync } from "node:child_process";
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { is } from "drizzle-orm";
import { getTableConfig, SQLiteTable } from "drizzle-orm/sqlite-core";

import app, { OPENAPI_INFO } from "../apps/api/src/index";
import { ERROR_CODES } from "../apps/api/src/http/schemas";
import * as schema from "../apps/api/src/db/schema";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

/** Every generated file says so on its first line, in that format's comment syntax. */
const WARNING = "Generated by `npm run gen`. Do not edit; edit the source it is derived from.";

function write(relative: string, contents: string): void {
  const path = join(ROOT, relative);
  mkdirSync(dirname(path), { recursive: true });
  // Always LF: .gitattributes normalises, and a CRLF write on Windows would
  // make `git diff --exit-code` fail in CI for a file nobody changed.
  writeFileSync(path, contents.replace(/\r\n/g, "\n"), "utf8");
  console.log(`  ${relative}`);
}

// ---------------------------------------------------------------------------
// The serving contract
// ---------------------------------------------------------------------------

function openApiDocument(): string {
  // The same object the Worker serves, imported rather than restated. A second
  // copy here would drift, and the test that compares the committed file to the
  // served document would then fail for a reason that has nothing to do with
  // the API's surface.
  return `${JSON.stringify(app.getOpenAPI31Document(OPENAPI_INFO), null, 2)}
`;
}

// ---------------------------------------------------------------------------
// The error catalogue
// ---------------------------------------------------------------------------

function anchorFor(code: string): string {
  // Must match `problem()`'s construction exactly, or every `type` link in
  // every error response points at an anchor this file does not contain.
  return code.toLowerCase().replace(/_/g, "-");
}

function errorsDocument(): string {
  const lines = [
    `<!-- ${WARNING} Source: apps/api/src/http/schemas.ts -->`,
    "",
    "# Errors",
    "",
    "Every non-2xx response is an RFC 9457 `application/problem+json` document:",
    "",
    "```json",
    "{",
    '  "type": "…/docs/errors.md#no-such-anchor",',
    '  "title": "Human-readable summary",',
    '  "status": 404,',
    '  "code": "MACHINE_READABLE_CODE",',
    '  "detail": "What specifically went wrong."',
    "}",
    "```",
    "",
    "Branch on `code`, never on `detail` — `detail` names the specific input and",
    "changes between requests. Some codes carry additional members, listed below.",
    "",
    "| Code | Status | When |",
    "| --- | --- | --- |",
  ];

  for (const [code, entry] of Object.entries(ERROR_CODES)) {
    lines.push(`| [\`${code}\`](#${anchorFor(code)}) | ${entry.status} | ${entry.when} |`);
  }

  lines.push("");

  for (const [code, entry] of Object.entries(ERROR_CODES)) {
    const extensions = (entry as { extensions?: readonly string[] }).extensions;
    lines.push(
      `## ${anchorFor(code)}`,
      "",
      `**\`${code}\`** — ${entry.status} ${entry.title}`,
      "",
      entry.when,
      "",
      entry.action,
      ""
    );
    if (extensions?.length) {
      lines.push(`Additional members: ${extensions.map((name) => `\`${name}\``).join(", ")}.`, "");
    }
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// The data dictionary
// ---------------------------------------------------------------------------

type Sidecar = { table: string; n_rows: number; content_hash: string };

function goldContracts(): Map<string, Sidecar> {
  const directory = join(ROOT, "data", "gold", "_contracts");
  const found = new Map<string, Sidecar>();
  try {
    for (const name of readdirSync(directory)) {
      if (!name.endsWith(".json")) continue;
      const sidecar = JSON.parse(readFileSync(join(directory, name), "utf8")) as Sidecar;
      found.set(sidecar.table, sidecar);
    }
  } catch {
    // Gold is committed, but a shallow checkout or a fresh clone mid-build can
    // legitimately lack it. The dictionary is still worth generating from the
    // schema alone, so this degrades rather than fails.
  }
  return found;
}

function dataDictionary(): string {
  const contracts = goldContracts();
  const lines = [
    `<!-- ${WARNING} Source: apps/api/src/db/schema.ts -->`,
    "",
    "# Data dictionary",
    "",
    "The tables the Worker reads. All of them are **derived** — every row is",
    "written by `hoopslab export` from committed gold parquet, and nothing but",
    "that command writes to this database. Row counts, where shown, come from the",
    "committed contract sidecars in `data/gold/_contracts/` and describe the full",
    "snapshot; the hosted demo serves a smaller slice.",
    "",
  ];

  const tables = Object.entries(schema)
    // `is()` rather than a duck-type check on the internal brand: the brand is
    // not part of Drizzle's public surface, and a silent mismatch here produces
    // an empty dictionary rather than an error — which is exactly what it did.
    .filter((entry): entry is [string, SQLiteTable] => is(entry[1], SQLiteTable))
    .map(([exportName, table]) => ({ exportName, config: getTableConfig(table) }))
    .sort((a, b) => a.config.name.localeCompare(b.config.name));

  for (const { config } of tables) {
    const sidecar = contracts.get(config.name);
    lines.push(`## \`${config.name}\``, "");
    if (sidecar) {
      lines.push(`${sidecar.n_rows.toLocaleString("en-GB")} rows in the full snapshot.`, "");
    }
    lines.push("| Column | Type | Null | Notes |", "| --- | --- | --- | --- |");

    for (const column of config.columns) {
      const notes: string[] = [];
      if (column.primary) notes.push("primary key");
      const reference = config.foreignKeys
        .flatMap((key) => {
          const { columns, foreignColumns } = key.reference();
          return columns.some((c) => c.name === column.name)
            ? [
                `→ \`${foreignColumns[0]?.table ? getTableConfig(foreignColumns[0].table as SQLiteTable).name : "?"}.${foreignColumns[0]?.name}\``,
              ]
            : [];
        })
        .at(0);
      if (reference) notes.push(reference);

      lines.push(
        `| \`${column.name}\` | ${column.getSQLType()} | ${column.notNull ? "no" : "yes"} | ${notes.join(", ")} |`
      );
    }
    lines.push("");
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------

console.log("Generating:");

const spec = "contracts/openapi.json";
write(spec, openApiDocument());
write("docs/errors.md", errorsDocument());
write("docs/data-dictionary.md", dataDictionary());

// openapi-typescript is a separate process rather than a library call: its
// programmatic API returns an AST that still needs printing, and shelling out
// keeps this script's only job the thing it is named for.
//
// Spawned as `node <path to cli>` rather than through npx or the .bin shim.
// Both of those are .cmd files on Windows, which execFileSync cannot spawn
// without a shell, and running a shell would put this repo's path into a
// command line — the working copy lives under "OneDrive\Belgeler", and
// quoting that correctly on two platforms is a problem worth not having.
// The path is hardcoded rather than resolved because the package's `exports`
// map does not expose bin/cli.js as a subpath, so require.resolve fails on it.
const client = "apps/web/src/lib/api/generated/types.ts";
mkdirSync(join(ROOT, dirname(client)), { recursive: true });
execFileSync(
  process.execPath,
  [join(ROOT, "node_modules", "openapi-typescript", "bin", "cli.js"), spec, "-o", client],
  { cwd: ROOT, stdio: "pipe" }
);
console.log(`  ${client}`);
