import type { D1Migration } from "@cloudflare/vitest-pool-workers";
import { applyD1Migrations, env } from "cloudflare:test";
import { beforeAll } from "vitest";
import type { Env } from "../src/env";
import seedSql from "./fixtures/seed.sql?raw";

/**
 * pool-workers 0.21 types `env` as `Cloudflare.Env`, a namespace normally
 * generated by `wrangler types`. Rather than commit a generated file or
 * augment a namespace the linter cannot parse, the shape is asserted once,
 * here, against the Worker's own `Env` — so the bindings still have exactly
 * one definition in `src/env.ts`.
 */
const testEnv = env as unknown as Env & { TEST_MIGRATIONS: D1Migration[] };

/**
 * Applies the real migrations, then loads a deterministic slice of the real
 * data.
 *
 * Two consequences worth stating. The migrations are exercised on every test
 * run, so a broken one fails here rather than in production. And the fixture is
 * generated from the committed snapshot by `hoopslab fixture` rather than typed
 * by hand — hand-written fixtures encode the author's assumptions about the
 * data, and this project exists because those assumptions were wrong.
 */
beforeAll(async () => {
  await applyD1Migrations(testEnv.DB, testEnv.TEST_MIGRATIONS);

  // The artefact is one transaction; workerd's D1 binding takes statements
  // individually, so the wrapper is stripped and the body replayed.
  const statements = seedSql
    .replace(/^BEGIN TRANSACTION;/m, "")
    .replace(/^COMMIT;/m, "")
    .split(/;\s*$/m)
    .map((statement: string) => statement.trim())
    .filter((statement: string) => statement.length > 0 && !statement.startsWith("--"));

  for (const statement of statements) {
    await testEnv.DB.prepare(statement).run();
  }
});
